@host = http://localhost:5064
@email = test@example.com
@password = 12345678

### 1) Регистрация
POST {{host}}/auth/create_user
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### 2) Логин (достанем accessToken в переменную token)
# @name login
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {% client.global.set("token", response.body.accessToken); %}

### 3) Проверка авторизации
GET {{host}}/auth/test
Authorization: Bearer {{token}}

### 4) Создать короткую ссылку (ВАЖНО: shortCode обязателен в твоей модели)
# @name createLink
POST {{host}}/links/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "originalUrl": "https://docs.google.com/document/d/1t1pSWfwaMs2XouBb_gUbHfZPSXc_gj0o4NIgug9wXJs/mobilebasic",
  "shortCode": "Abc"
}

### 5) Получить QR (публично)
GET {{host}}/Abc123/qr?size=280

### 6) Редирект (публично + запишет клик)
GET {{host}}/Abc123
